project_id = "oaevszkqyzfewazfioyy"

[functions.register-nps]
verify_jwt = false

[functions.voice-assistant]
verify_jwt = false

[functions.parse-invoice]
verify_jwt = false

[functions.register-user]
verify_jwt = false

[functions.manage-user]
verify_jwt = false
