project_id = "oaevszkqyzfewazfioyy"

[functions.register-nps]
verify_jwt = false

[functions.voice-assistant]
verify_jwt = false

[functions.parse-invoice]
verify_jwt = false

[functions.register-user]
verify_jwt = false

[functions.manage-user]
verify_jwt = false

[functions.generate-report]
verify_jwt = false

[functions.send-slack-notification]
verify_jwt = false

[functions.list-slack-channels]
verify_jwt = false
